import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import TodoistImage from "../../public/images/todoist.png";
import DropboxImage from "../../public/images/dropbox.png";
import DarkmodeToggle from "./DarkmodeToggle";
import Greeting from "./Greeting";
import NavBar from "./NavBar";
import Introduction from "./Introduction";
import Inventions from "./Inventions";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen items-start justify-center bg-amber-100 font-mono text-zinc-900 dark:bg-[#282828] dark:text-[#b8bb26]">
        <div className="container flex w-full flex-col items-center justify-center gap-6 px-4 py-8 ">
          <Greeting />
          <div className="flex w-full flex-row items-center justify-center gap-32 p-2 dark:bg-[#8ec07c] dark:text-[#282828] sm:gap-64 ">
            <NavBar />
            <DarkmodeToggle />
          </div>
          <Introduction />
          <Inventions />
        </div>
      </main>
    </>
  );
};

export default Home;
