import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import DarkmodeToggle from "./DarkmodeToggle";
import Greeting from "./Greeting";
import NavBar from "./NavBar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-start justify-start bg-amber-100 text-zinc-900 dark:bg-gray-900 dark:text-amber-100">
        <div className="container flex flex-col items-center justify-center gap-6 px-4 py-8 ">
          <Greeting />
          <DarkmodeToggle />
          <NavBar />
        </div>
      </main>
    </>
  );
};

export default Home;
