import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import DarkmodeToggle from "./DarkmodeToggle";
import Greeting from "./Greeting";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-cyan-50 text-zinc-900 dark:bg-zinc-900 dark:text-zinc-300 ">
        <Greeting />
        <DarkmodeToggle />
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 "></div>
      </main>
    </>
  );
};

export default Home;
